#!/usr/bin/env python3
"""Package the stress-pack CSVs as .xlsx sample workbooks.

The CSVs stay the source of truth (regenerated by gen_stress_pack.py); this
script only re-dresses them as the Excel files people actually download and
try. Realism rule: anything that parses as a clean number is written as a
number, everything else — currency strings, "(500)", " 5 " padding, "7 days",
"N/A", dates — is written as literal text, so every planted trap survives the
round trip back through the engine's parser. No formulas anywhere, on purpose:
these are data files, and the traps must reach the engine raw.

Usage: python3 make_xlsx_pack.py [dir-with-csvs]   (default: this directory)
"""
import csv
import os
import sys

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

FILES = {
    "apparel_mis_messy.csv": "Apparel MIS",
    "footwear_mis_messy.csv": "Footwear MIS",
    "electronics_mis_messy.csv": "Electronics MIS",
    "beauty_mis_messy.csv": "Beauty MIS",
    "home_decor_mis_messy.csv": "Home & Decor MIS",
    "sports_mis_messy.csv": "Sports MIS",
    "books_stationery_mis_messy.csv": "Books MIS",
    "jewellery_mis_messy.csv": "Jewellery MIS",
    "mega_mix_mis.csv": "Stock Report",
    "corrupted_mis.csv": "Weekly Stock Report",
}

BODY = Font(name="Arial", size=10)
HEAD = Font(name="Arial", size=10, bold=True, color="FFFFFF")
HEAD_FILL = PatternFill("solid", fgColor="8B1E1E")


def cell_value(raw):
    """Number if the text is a clean number, else the literal text (trap)."""
    s = raw
    if s == "" or s != s.strip():          # blanks and padded strings stay text
        return s
    try:
        n = int(s)
        return n if str(n) == s else s      # "007" or "1,240" stay text
    except ValueError:
        pass
    try:
        f = float(s)
        # only accept the plain decimal form; keep "1e3", "nan", "inf" as text
        if s.replace(".", "", 1).lstrip("-").isdigit():
            return f
    except ValueError:
        pass
    return s


def convert(csv_path, xlsx_path, sheet_name, banner_file=False):
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))
    header_at = 3 if banner_file else 1     # corrupted file: banner rows above
    widths = {}
    for r, row in enumerate(rows, start=1):
        for c, raw in enumerate(row, start=1):
            cell = ws.cell(row=r, column=c, value=cell_value(raw))
            cell.font = HEAD if r == header_at else BODY
            if r == header_at:
                cell.fill = HEAD_FILL
            widths[c] = max(widths.get(c, 6), min(len(str(raw)) + 2, 26))
    for c, w in widths.items():
        ws.column_dimensions[get_column_letter(c)].width = w
    ws.freeze_panes = ws.cell(row=header_at + 1, column=1)
    wb.save(xlsx_path)
    return len(rows) - 1


def main():
    d = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
    for name, sheet in FILES.items():
        src = os.path.join(d, name)
        dst = os.path.splitext(src)[0] + ".xlsx"
        n = convert(src, dst, sheet, banner_file=(name == "corrupted_mis.csv"))
        print(f"{os.path.basename(dst):40s} {n:>6d} rows")


if __name__ == "__main__":
    main()
